# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('plan_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=32)),
                ('one_week_price', models.IntegerField(default=0)),
                ('one_month_price', models.IntegerField(default=0)),
                ('three_month_price', models.IntegerField(default=0)),
                ('one_year_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='plan_joined',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='termDBFront.Plan'),
        ),
    ]
