# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termDBFront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=512)),
                ('date_published', models.DateField()),
                ('date_update', models.DateField()),
                ('term_path', models.CharField(max_length=512)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termDBFront.Company')),
                ('tags', models.ManyToManyField(to='termDBFront.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='plan_joined',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
