# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termDBFront', '0003_auto_20170129_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term_path',
            field=models.CharField(max_length=512),
        ),
        migrations.DeleteModel(
            name='TermData',
        ),
    ]
