# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:20
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('termDBFront', '0005_auto_20170129_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termdata',
            name='path',
        ),
        migrations.AddField(
            model_name='termdata',
            name='content',
            field=tinymce.models.HTMLField(default='none'),
            preserve_default=False,
        ),
    ]
