# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('termDBFront', '0006_auto_20170129_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='termdata',
            name='title',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='termdata',
            name='content',
            field=tinymce.models.HTMLField(default='none'),
        ),
    ]
