# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('termDBFront', '0007_auto_20170129_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termdata',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='termdata',
            name='title',
            field=models.CharField(default='タイトルを入力', max_length=512),
        ),
    ]
